config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index'  
  resources :departments 
  resources :roles
  

  devise_scope :user do
    root :to => "devise/sessions#new"
    get '/users', to: 'devise/registrations#new'
    # get '/users/password', to: 'devise/passwords#new'
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tickets, param: :slug do
    member do
      patch :upgrade
      patch :status_transistion
    end
    resources :messages
  end

  get '/ticket/:department_selected_option', to: 'tickets#fetch'
  
end







# devise_for :users, :controllers => {:registrations => "registrations"}
  #        :skip => [:registrations]
        

  # devise_scope :user do
  #   get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
  #   post "user/sign_up", to: "users/registrations#create", as: :user_registration
  #   get "user/edit", to: "users/registrations#edit", as: :edit_user_registration
  # end

  # get 'home/index' , to: 'home#index'
  # get 'home/show',to: 'home#show'
  # get '/home/:department_selected_option', to: 'home#fetch'
  
  # resources :users

app/models/department.rb
class Department < ApplicationRecord
  before_save :capitalize_name
  
  has_many :users, dependent: :destroy

  validates :department_name, presence: true, uniqueness: true

  private 
  def capitalize_name
    self.department_name = self.department_name.capitalize 
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: %i[show edit update destroy]
  
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path, notice: "New #{@department.department_name} is successfully created"
    else
      render :new, status: unprocessable_entity, alert: 'Unable to create Department.Try again..'
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path, notice: "#{@department.department_name} is succesfully updated"
    else
      render :edit, status: unprocessable_entity, alert: 'Unable to edit Department.Try again..'
    end
  end

  def destroy
    if @department.destroy
      redirect_to departments_path, notice: "#{@department.department_name} is succesfully deleted"
    else
      redirect_to departments_path, alert: "#{@department.department_name} cannot be deleted"
    end
  end

  private

  def set_department
    @department = Department.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to departments_path, notice: 'Record Not Found.'
  end

  def department_params
    params.require(:department).permit(:department_name)
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<div class="card form-box" >
  <% if department.new_record? %>
    <h2>New Department</h2>
  <% else %>
    <h2>Update Department</h2>
  <% end %>
  <br>
  <%= form_with model: department do | f | %>
    <div class="field">
      <%= f.text_field :department_name, autofocus: true, autocomplete: "email", class:"form-control",placeholder:"Department name" %>
      <% department.errors.full_messages_for(:department_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit class:"form-control btn-info"%>
    </div>
  <% end %>
</div>


<!--
<%= form_with model: department do | f | %>
  <%= f.label :department_name %>
  <%= f.text_field :department_name %>
  <% department.errors.full_messages_for(:department_name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <%= f.submit %>
<% end %>
-->

app/views/departments/edit.html.erb
<%= render 'form', department: @department %>

app/views/departments/index.html.erb
<h4 class="index-heading" > All Department : </h4>
<%= link_to "New Department", new_department_path , class:"btn btn-info mb-3 new-department-btn"%>

<table class="table table-box">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do | department | %>
      <tr>
        <td><%= department.department_name %></td>
        <td><%= link_to "Edit", edit_department_path(department) %> |
        <%= link_to "Delete", department_path(department), method: :delete, data: { confirm: "Are you sure ? All User and thier activity will also be deleted. "} %><br></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<%= render 'form', department: @department %>