config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index'  
  resources :departments 
  resources :roles
  

  devise_scope :user do
    root :to => "devise/sessions#new"
    get '/users', to: 'devise/registrations#new'
    # get '/users/password', to: 'devise/passwords#new'
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tickets, param: :slug do
    member do
      patch :upgrade
      patch :status_transistion
    end
    resources :messages
  end

  get '/ticket/:department_selected_option', to: 'tickets#fetch'
  
end







# devise_for :users, :controllers => {:registrations => "registrations"}
  #        :skip => [:registrations]
        

  # devise_scope :user do
  #   get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
  #   post "user/sign_up", to: "users/registrations#create", as: :user_registration
  #   get "user/edit", to: "users/registrations#edit", as: :edit_user_registration
  # end

  # get 'home/index' , to: 'home#index'
  # get 'home/show',to: 'home#show'
  # get '/home/:department_selected_option', to: 'home#fetch'
  
  # resources :users

app/models/ticket.rb
class Ticket < ApplicationRecord
  before_save :add_due_date,if: :new_record? || :assigned_to_changed?
  extend FriendlyId
  friendly_id :generated_slug, use: :slugged

  # Validations
  validates :subject ,:description ,:department_id, :assigned_to, :priority , presence: true
  
  # Associations
  has_many :messages , dependent: :destroy
  belongs_to :creator,class_name: 'User'
  belongs_to :assigned_to ,class_name: 'User'  
  belongs_to :department 
  has_many :ticket_histories, dependent: :destroy

  # attachment
  has_many_attached :documents

  # Scopes
  scope :user_assigned_tickets, ->(current_user) { current_user.assigned_tickets.where("status = 'in_progress' or status = 'closed'") }
  scope :new_request_tickets, ->(current_user) { current_user.assigned_tickets.where("status = 'open' or status = 're_open'") }
  scope :order_by_due_date_and_priority, ->(tickets) { 
    tickets.order(
      due_date: :asc).order(
      Arel.sql(<<-SQL.squish 
        CASE 
        WHEN priority = 'High' THEN '1' 
        WHEN priority = 'Medium' THEN '2' 
        WHEN priority = 'Low' THEN '3' 
        END 
      SQL
      ) ) 
    }

  # AASM code
  include AASM 

  aasm column: :status do
    state :open,initial: true
    state :in_progress , :rejected , :pending , :closed , :re_open

    event :accept do 
      transitions from: [:open , :re_open ] , to: :in_progress
    end

    event :reject do 
      transitions from: [ :open , :re_open ] , to: :rejected
    end

    event :after_due_date do 
      transitions from: [ :in_progress ] , to: :pending
    end

    event :satisfy do 
      transitions from: [ :in_progress , :pending ] , to: :closed
    end

    event :upgrade do 
      transitions from: [:pending , :in_progress, :rejected , :closed ] , to: :re_open
    end

    event :close do 
      transitions from: [:open , :re_open , :rejected ] , to: :closed
    end
  end

  def add_due_date
    self.due_date = (Date.today() + 3).to_s
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

# This controller is user for handling Tickets
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_ticket, only: %i[show edit update destroy status_transistion upgrade]

  def index
    @tickets = Ticket.ransack(params[:q])
    @user_tickets = TicketManager::UserTicketFinder.call(current_user, params[:q])
    @assigned_tickets = TicketManager::UserAssignedTicketFinder.call(current_user, params[:q])
    @new_request_tickets = TicketManager::NewRaisedTicketFinder.call(current_user, params[:q])
  end

  def show
    @ticket_assigned_history = TicketManager::TicketHistories.call(@ticket)
    @ticket_messages = @ticket.messages
  end

  def new
    @ticket = current_user.tickets.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      TicketManager::SendMailAndCreateHistory.call(@ticket)
      redirect_to tickets_path, notice: t('notice.new_ticket')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @ticket.update(ticket_params)
      TicketManager::SendMailAndCreateHistory.call(@ticket, current_user)
      @ticket.upgrade!
      redirect_to @ticket, notice: t('notice.ticket_updated')
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path, notice: t('notice.ticket_deleted')
  end

  def fetch
    assign_to = TicketManager::UserFinder.call(selected_department_params)
    render json: assign_to.to_json(only: %i[id name])
  end

  def status_transistion
    if TicketManager::PerformTransistion.call(params[:transistion], @ticket)
      redirect_to @ticket
    else
      redirect_to @ticket, notice: t('notice.transistion_failed')
    end
  end

  def upgrade
    if TicketManager::FindSuperior.call(@ticket)
      if @ticket.save
        TicketManager::SendMailAndCreateHistory.call(@ticket, current_user)
        @ticket.upgrade!
        redirect_to @ticket, notice: t('notice.ticket_upgraded')
      else
        redirect_to @ticket, alert: t('notice.ticket_upgrade_failed')
      end
    else
      redirect_to @ticket, alert: t('notice.top_level_ticket')
    end
  end

  private

  def find_ticket
    @ticket = Ticket.friendly.find(params[:slug])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to tickets_path, notice: "Something went wrong"
  end

  def ticket_params
    params.require(:ticket).permit(:subject, :description, :due_date, :priority, :department_id,
                                   :assigned_to_id, :user_id, documents: [])
  end

  def selected_department_params
    params.permit(:department_selected_option)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_assigned_tickets_table.html.erb
<div class="ticket-table-box">
  <table class="table table-striped table-striped-bg">
    <thead class="table-head">
      <tr>
        <th> Subject </th>
        <% if tickets.first.creator == current_user  %>
          <th> Assigned to </th>
        <% else %>
          <th> Assigned By </th>
        <% end %>
        <th> Priority </th>
        <th> Status </th>
      </tr>
    </thead>
    <tbody>
    <% tickets.each do |ticket| %>
        <tr onclick="location.href='<%= ticket_path(ticket)%>'"  >
          <td><%= link_to ticket.subject, ticket %></td>
          <% if tickets.first.creator == current_user  %>
            <td><%= ticket.assigned_to.name %></td> 
          <% else %>
            <td><%= ticket.creator.name %></td> 
          <% end %>
          <% if ticket.priority == "High"%>
            <td><span class="badge high-priority-badge"><%= ticket.priority %></span></td>
          <% elsif ticket.priority == "Medium" %>
            <td><span class="badge medium-priority-badge "><%= ticket.priority %></span></td>
          <% else %>
            <td><span class="badge low-priority-badge " ><%= ticket.priority %></span></td>
          <% end %>

          <% if ticket.status == "open"%>
            <td><span class="badge open-status-badge">Open</span></td>
          <% elsif ticket.status == "in_progress" %>
            <td><span class="badge in-progress-status-badge">In Progress</span></td>
          <% elsif ticket.status == "rejected" %>
            <td><span class="badge rejected-status-badge">Rejected</span></td>
          <% elsif ticket.status == "closed" %>
            <td><span class="badge closed-status-badge" >Closed</span></td>
          <% elsif ticket.status == "re_open" %>
            <td><span class="badge reopen-status-badge" >Re Opened</span></td>
          <% else %>
            <td><span class="badge"><%= ticket.status %></span></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/_documents_attached.html.erb
<% if model_instance.documents.attached? %>
    <%if model_instance.class.to_s == "Ticket" %>
        <p class="lead">
            <strong> Attachments : </strong> 
        </p>
    <% end %>
    <% model_instance.documents.each do |document|%>
        <%= link_to document.filename, rails_blob_path(document, disposition: 'inline') %> | 
    <% end %>
<% end %>

app/views/tickets/_form.html.erb
<div class="container form-box">

  <%= form_with model: ticket do |f| %>
    <div class="row g-3">
      <div class="col-md-6">
        <%= f.label :department_id,class:"form-label" %><br />
        <%= f.select :department_id, options_for_select( get_departments ),{prompt: 'Select department'}, class: 'form-control' %>
        <% ticket.errors.full_messages_for(:department_id).each do |message| %>
          <p class="text-danger"> <%= message %> </p>
        <% end %>
      </div>

      <div class="col-md-6">
        <%= f.label :assigned_to,class:"form-label" %><br />
          <%= f.select :assigned_to_id, options_for_select("None"),{} , class: 'form-control' %>
          <% ticket.errors.full_messages_for(:assigned_to_id).each do |message| %>
            <p class="text-danger"> <%= message %> </p>
          <% end %>
      </div>

      <div class="col-md-6">
        <%= f.label :Subject ,class:"form-label"%><br />
        <%= f.text_field :subject,class:"form-control", autofocus: true%>
        <% ticket.errors.full_messages_for(:subject).each do |message| %>
          <p class="text-danger"> <%= message %> </p>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :description ,class:"form-label" %><br />
        <%= f.text_field :description, class:"form-control",  autocomplete: "email" %>
        <% ticket.errors.full_messages_for(:description).each do |message| %>
          <p class="text-danger"> <%= message %> </p>
        <%end%>
      </div>
<!--
      <div class="col-md-6">
        <%= f.label :due_date , class:"form-label" %><br />
        <%= f.date_field :due_date ,class:"form-control" %>
        <% ticket.errors.full_messages_for(:due_date).each do |message| %>
          <p class="text-danger"> <%=message%> </p>
        <%end%>
      </div>
-->
      <div class="col-md-6">
        <%= f.label :priority,class:"form-label" %><br />
        <%= f.select :priority, options_for_select(["High" ,"Medium" ,"Low"]),{prompt: 'Select priority'},{class: 'form-control'} %>
        <% ticket.errors.full_messages_for(:priority).each do |message| %>
          <p class="text-danger"> <%= message %> </p>
        <%end%>
      </div>

      <div class="col-md-6">
        <%= f.label :documents,class:"form-label" %><br />
        <%= f.file_field :documents, multiple: true, class: "form-control"%>
      </div>

      <div class="col-12">
        <br>
        <%= f.submit class:"btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    $('#ticket_department_id').on('change',function(){
      var department_selected_option = $(this).val();

      if (department_selected_option){
        $.ajax({
          url: '/ticket/' + department_selected_option,
          type: 'GET',
          dataType: 'json',
          success: function(data){
            var options_html ='';
            $.each(data, function(index,value){
                options_html += '<option value="' + value.id + '">' + value.name + '</option>';
            });
            $('#ticket_assigned_to_id').html(options_html);
            console.log(data);
          }, 
          error: function(xhr, textStatus, errorThrown) {
                        console.log('Error fetching options: ' + errorThrown);
                    }
        });
      }
    });
  });
</script>

app/views/tickets/_trasistions_button.html.erb
<% if( ( ticket.status == "open" or ticket.status == "re_open" ) and ( ticket.assigned_to_id == current_user.id )) %>
  <%= button_to "Accept", status_transistion_ticket_path( ticket, transistion:"accept" ), method: :patch, class: "btn btn-primary mb-4 rounded-0" %>
  
  <%= button_to "reject", status_transistion_ticket_path( ticket, transistion:"reject" ), method: :patch, class: "btn btn-primary mb-4 rounded-0" %>

<% elsif ( ticket.status == "in_progress" or ticket.status == "pending" ) and ( ticket.creator_id == current_user.id ) %>
  <%= button_to "Satisfy and close", status_transistion_ticket_path( ticket, transistion:"satisfy" ), method: :patch, class: "btn btn-primary mb-4 rounded-0"%>
  <%= button_to "upgrade", upgrade_ticket_path(ticket), method: :patch, class: "btn btn-primary mb-4 rounded-0"%>

<% elsif ( ticket.status == "rejected" ) and ( ticket.creator_id == current_user.id ) %>
  <%= button_to "Close", status_transistion_ticket_path( ticket, transistion:"close" ), method: :patch, class: "btn btn-primary mb-4 rounded-0" %>
  <%= button_to "upgrade and re_open ", edit_ticket_path(ticket), method: :get, class: "btn btn-primary mb-4 rounded-0"%>

<% elsif ( ticket.status != "closed" ) and ( ticket.creator_id == current_user.id ) %>
  <%= button_to "close", status_transistion_ticket_path( ticket, transistion:"close" ), method: :patch, class: "btn btn-primary mb-4 rounded-0"%>
 
<% end %>

app/views/tickets/edit.html.erb
<%= render 'form', {ticket: @ticket } %>

app/views/tickets/index.html.erb
<div class="container-fluid ticket_list">
  <div class="row">
    <div class="col-3 rooms-sidebar">
      <%= search_form_for @tickets do |f| %>
        <%= f.search_field :subject_cont, class:"form-control search", placeholder: "Search by Subject.." %>
        <%= f.submit "Search", class:"btn btn-primary" %>
      <% end %>
        <br>
      <%= link_to "New ticket", new_ticket_path, class: "btn btn-info mb-3 ml-1 rounded-2 form-control" %>
      <ul class="nav nav-pills mb-3 nav-pills-block" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active form-control m-1" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Your Tickets</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link form-control m-1" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Tickets Assigned to you </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link form-control m-1" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">New Request</button>
        </li>
      </ul>
    </div>
    <div class="col-9 ticket-box">
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <% if @user_tickets&.first == nil %>
            <h4 class="text-light"> You have not created any ticket. </h4>
          <% else %>
            <%= render 'assigned_tickets_table', { tickets: @user_tickets } %>
          <% end %>
        </div>

        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          <% if @assigned_tickets&.first == nil %>
            <h4 class="text-light"> No one has assigned any ticket to you </h4>
          <% else %>
              <%= render 'assigned_tickets_table', {tickets: @assigned_tickets } %>
          <% end %>
        </div>

        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
          <% if @new_request_tickets&.first == nil %>
            <h4  class="text-light"> No new request available </h4>
          <% else %>
            <%= render 'assigned_tickets_table', { tickets: @new_request_tickets } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tickets/new.html.erb
<%= render 'form' , { ticket: @ticket }%>

app/views/tickets/show.html.erb
<div id="user-id" data-user-id=" <%= current_user.id %> "> </div>
<div id="ticket-id" data-ticket-id=" <%= @ticket.id %> "> </div>

<div class="container-fluid ticket-box">
  <div class="row">
    <div class="col-5 rooms-sidebar">
        <div class="card-body card-body-bg">
          <h2 class="text-center">Ticket Details</h2>
          <p class="lead">
            <strong> Subject : </strong> <%= @ticket.subject %> 
          </p>
          <p class="lead">
            <strong> Description : </strong> <%= @ticket.description %> 
          </p>
          <p class="lead">
            <strong> Due Date : </strong> <%= @ticket.due_date.strftime("%d-%m-%Y") %> 
          </p>
          <p class="lead">
            <strong> Priority : </strong> <%= @ticket.priority %> 
          </p>
          <% if current_user.id == @ticket.creator_id %>
            <p class="lead">
              <strong> Assigend to : </strong> <%= @ticket.assigned_to.name %> 
            </p>
          <%else%>
            <p class="lead">
              <strong> Assigend By : </strong> <%= @ticket.creator.name %> 
            </p>
          <%end%>
          <%= render 'documents_attached', { model_instance: @ticket }%>
          <br>
          <%= render 'trasistions_button', { ticket: @ticket }%> 
          <%= render 'ticket_histroies/time_line.html', { ticket_assigned_history: @ticket_assigned_history } %>
        </div>
    </div>
    <div class="col-7 chat-box">
        <% if @ticket.present? %>
          <div class="chat-room">
            <nav class="navbar navbar-light">
              <span class="navbar-brand" href="#">
                <b><%= @ticket.subject %></b>
              </span>
            </nav>
            <div class="message-box"> 
              <div id="messages">
                <%= render 'messages/message', ticket_messages: @ticket_messages %>
              </div>
            </div>
            <div class="new-message-box">
              <%= form_with(model: [@ticket, @ticket.messages.build]) do | f |%>
                <p>
                  <br>
                  <div class="row">
                    <div class="col-9 pr-0">
                      <%= f.text_field :content, id: 'message_content', class: 'form-control' %> 
                    </div>
                    <div class="col-1 p-0">
                        <%= f.label :documents, "📎", class:"form-label file-field" %>
                        <%= f.file_field :documents, multiple: true, class: "form-select" %>
                    </div>
                    <div class="col-2 p-0">
                      <%= f.submit "Send", data: { disable_with: false }, class:"btn btn-primary", id:"send" %>
                    </div>
                  </div>
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

<script>
  $('.message-box').stop().animate ({
    scrollTop: $('.message-box')[0].scrollHeight
  });

  $("#send").click(function() {
    $(".message-box").stop().animate ({ 
      scrollTop: $(".message-box")[0].scrollHeight
      }, 500);
  });
</script>