config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index'  
  resources :departments 
  resources :roles
  

  devise_scope :user do
    root :to => "devise/sessions#new"
    get '/users', to: 'devise/registrations#new'
    # get '/users/password', to: 'devise/passwords#new'
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tickets, param: :slug do
    member do
      patch :upgrade
      patch :status_transistion
    end
    resources :messages
  end

  get '/ticket/:department_selected_option', to: 'tickets#fetch'
  
end







# devise_for :users, :controllers => {:registrations => "registrations"}
  #        :skip => [:registrations]
        

  # devise_scope :user do
  #   get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
  #   post "user/sign_up", to: "users/registrations#create", as: :user_registration
  #   get "user/edit", to: "users/registrations#edit", as: :edit_user_registration
  # end

  # get 'home/index' , to: 'home#index'
  # get 'home/show',to: 'home#show'
  # get '/home/:department_selected_option', to: 'home#fetch'
  
  # resources :users

app/models/role.rb
class Role < ApplicationRecord
  has_ancestry

  validates :name, presence: true

  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  
  
  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ edit update destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
    @roles = Role.all
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path, notice: "New #{@role.name} role is created"
    else
      render :new
    end
  end

  def edit
    @roles = Role.all
  end

  def update
    if @role.update(role_params)
      redirect_to roles_path, notice: "#{@role.name} is successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_path, notice: "#{@role.name} is successfully deleted"
  end

  private
  def set_role
    @role = Role.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to roles_path, notice: "Somtihng went wrong"
  end

  def role_params
    params.require(:role).permit(:name, :parent_id)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<div class="card form-box">
  <% if role.new_record? %>
    <h2>New Role</h2>
  <% else %>
    <h2>Update Role</h2>
  <% end %>
  <br>
  <%= form_with model: role do | f | %>
    <div class="field">
      <%= f.text_field :name, autofocus: true, autocomplete: "email", class:"form-control",placeholder:"Role name" %>
      <% role.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div class="field">
      <br>
      <%= f.select :parent_id, options_from_collection_for_select(@roles, "id", "name"),{prompt: 'Select Parent Role'}, class: 'form-control' %>
    </div>

    <br>
    <div class="actions">
      <%= f.submit class:"form-control btn-info"%>
    </div>
  <% end %>
</div>

app/views/roles/edit.html.erb
<%= render 'form' , role: @role %>

app/views/roles/index.html.erb
<h4> All Roles :</h4>
<%= link_to "New Role", new_role_path, class:"btn btn-info mb-3 new-role-btn"%>
<table class="table table-box">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td>
          <%= link_to "Edit", edit_role_path(role)  %> | <%= link_to "Delete", role_path(role), method: :delete,   data: { confirm: "Are you sure ? "} %><br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roles/new.html.erb
<%= render 'form', role: @role  %>